GET http://localhost:5502/
Accept: application/json
Authorization: Bearer <your-access-token>
X-Platform: yu2ahel


###

GET http://localhost:5502/demo
Accept: application/json
Authorization: Bearer <your-access-token>
X-Platform: yu2ahel


### Create a new profile
POST http://localhost:5502/api/v1/profile
Content-Type: application/json
Authorization: Bearer <your-access-token>
x-platform: fuse

{
  "name": "Hazem Safwat",
  "email": "hazem@example.com",
  "mobile": "1234567890",
  "gender": "male",
  "dob": "1990-01-01",
  "metadata": {
    "key1": "value1",
    "key2": "value2"
  },
  "additionalFields": {
    "field1": "value1",
    "field2": "value2"
  }
}



### Get all profiles
#?showHidden=false
GET http://localhost:5502/api/v1/profile
Accept: application/json
Authorization: Bearer <your-access-token>
x-platform: fuse



### Get a profile by ID
#?showHidden=false
@profileId = 66f4afb79cf5c2c99776186e
GET http://localhost:5502/api/v1/profile/{{profileId}}
Accept: application/json
Authorization: Bearer <your-access-token>
x-platform: fuse


### Update a profile by ID

PUT http://localhost:5502/api/v1/profile/{{profileId}}
Content-Type: application/json
Authorization: Bearer <your-access-token>
x-platform: fuse

{
  "name": "Mohamed ali"

}


### Delete a profile by ID
DELETE http://localhost:5502/api/v1/profile/{{profileId}}
Authorization: Bearer <your-access-token>
x-platform: fuse

###
